/**
 * Schema module: identity
 *
 * Phase 1 — implements the `users` table per Database Schema v1.0 Approved
 * §4.1 exactly. `id` is NOT auto-generated: it matches/equals the Supabase
 * Auth user id directly (no separate auth_identities table — §4.1 is the
 * persistence authority and does not define one). No password/credential
 * column exists here or anywhere in the product database.
 */
import { sql } from "drizzle-orm";
import { check, pgTable, text, timestamp, uuid } from "drizzle-orm/pg-core";

export const users = pgTable(
  "users",
  {
    /** Equals the Supabase Auth user id — never generated by this table. */
    id: uuid("id").primaryKey(),
    fullName: text("full_name").notNull(),
    /** Display-only mirror of the identity provider's email; not an auth source. */
    emailDisplay: text("email_display"),
    phone: text("phone"),
    // Teacher profile foundation (migration 0061). Stable codes only, validated
    // in the contracts (governorate / subject enums); `subject_other` holds the
    // free text when subject = 'OTHER'. Nullable — filled at Step-2 onboarding.
    governorate: text("governorate"),
    subject: text("subject"),
    subjectOther: text("subject_other"),
    status: text("status").notNull().default("ACTIVE"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().default(sql`now()`),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().default(sql`now()`),
  },
  (table) => [check("users_status_check", sql`${table.status} IN ('ACTIVE', 'DISABLED')`)],
);
