-- Billing Engine — Phase 4. subscription_periods: the IMMUTABLE commercial
-- period ledger, plus a minimal scheduled-downgrade pending-state on
-- subscriptions.
--
-- WHY a ledger (Phase-4 audit): `subscriptions` stores only a SINGLE current
-- commercial snapshot (one plan/price/period). That cannot faithfully represent
-- (a) stacked early renewals whose prepaid time spans MANY cycles, (b) a future
-- paid cycle at a DIFFERENT plan than the current one (early renewal after a
-- scheduled downgrade), or (c) exact upgrade proration across several prepaid
-- periods at different locked prices. This ledger records each paid commercial
-- period as an independent immutable fact so all of the above become exact.
--
-- MODEL (append-only, no row is ever split or mutated):
--   • NEW_SUBSCRIPTION / RENEWAL append ONE full-cycle period row.
--   • UPGRADE appends target-plan rows covering [now, period_end] of each
--     affected period; it NEVER mutates the originals. Precedence for "effective
--     plan at time t" is the HIGHEST `seq` among rows whose [period_start,
--     period_end) contains t — so the original still correctly describes the
--     already-elapsed [start, now] slice, and the upgrade row wins from `now`.
--   • Overlaps between an original and its upgrade row are INTENTIONAL; the
--     EFFECTIVE timeline (top-seq per instant) stays gapless + non-overlapping.
--   • `nominal_cycle_start/end` = the full cycle a (possibly partial) span
--     belongs to, so a partial upgrade span values exactly as
--     cycle_price_minor × (period_end-period_start)/(nominal_cycle_end-nominal_cycle_start).
--
-- Money = integer minor units (ADR-022). IMMUTABLE like subscription_payments:
-- no UPDATE / no DELETE grant for ANY app role; tenant SELECT own only; the
-- trusted billing writer (app_platform_admin) INSERTs; app_worker SELECTs (it
-- reads the ledger to promote a due future period into the current aggregate).
--
-- APPLY on a disposable/staging DB (with 0062-0065) before deploy. NOT
-- auto-applied to Production.

CREATE TABLE IF NOT EXISTS "subscription_periods" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "seq" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "workspace_id" uuid NOT NULL,
  "subscription_id" uuid NOT NULL,
  "plan_code" text NOT NULL,
  "billing_cycle" text NOT NULL,
  "cycle_price_minor" bigint NOT NULL,
  "currency_code" char(3) NOT NULL DEFAULT 'EGP',
  "plan_price_version" integer,
  "period_start" timestamptz NOT NULL,
  "period_end" timestamptz NOT NULL,
  "nominal_cycle_start" timestamptz NOT NULL,
  "nominal_cycle_end" timestamptz NOT NULL,
  "source_action" text NOT NULL,
  "source_payment_id" uuid,
  "supersedes_period_id" uuid,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "subscription_periods_workspace_id_workspaces_id_fk" FOREIGN KEY ("workspace_id") REFERENCES "public"."workspaces"("id") ON DELETE restrict,
  CONSTRAINT "subscription_periods_subscription_id_subscriptions_id_fk" FOREIGN KEY ("subscription_id") REFERENCES "public"."subscriptions"("id") ON DELETE restrict,
  CONSTRAINT "subscription_periods_source_payment_id_fk" FOREIGN KEY ("source_payment_id") REFERENCES "public"."subscription_payments"("id") ON DELETE restrict,
  CONSTRAINT "subscription_periods_supersedes_period_id_fk" FOREIGN KEY ("supersedes_period_id") REFERENCES "public"."subscription_periods"("id") ON DELETE restrict,
  CONSTRAINT "subscription_periods_plan_code_check" CHECK ("plan_code" IN ('STARTER', 'GROWTH', 'PROFESSIONAL', 'ADVANCED', 'BUSINESS', 'BUSINESS_PLUS', 'CUSTOM')),
  CONSTRAINT "subscription_periods_billing_cycle_check" CHECK ("billing_cycle" IN ('MONTHLY', 'ANNUAL')),
  CONSTRAINT "subscription_periods_source_action_check" CHECK ("source_action" IN ('NEW_SUBSCRIPTION', 'RENEWAL', 'UPGRADE')),
  CONSTRAINT "subscription_periods_price_nonnegative_check" CHECK ("cycle_price_minor" >= 0),
  CONSTRAINT "subscription_periods_span_check" CHECK ("period_end" > "period_start"),
  CONSTRAINT "subscription_periods_nominal_span_check" CHECK ("nominal_cycle_end" > "nominal_cycle_start")
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "subscription_periods_workspace_idx" ON "subscription_periods" ("workspace_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "subscription_periods_subscription_seq_idx" ON "subscription_periods" ("subscription_id", "seq");
--> statement-breakpoint
-- Effective-plan / active-period lookups by instant.
CREATE INDEX IF NOT EXISTS "subscription_periods_subscription_span_idx" ON "subscription_periods" ("subscription_id", "period_start", "period_end");
--> statement-breakpoint
-- Worker period-advance: find periods active at `now` (period_start <= now < period_end)
-- across tenants WITHOUT a full-table scan. Bounds the 60s advance query.
CREATE INDEX IF NOT EXISTS "subscription_periods_active_at_idx" ON "subscription_periods" ("period_start", "period_end");
--> statement-breakpoint
ALTER TABLE "subscription_periods" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
-- Tenant reads its own periods (read-only). No write path for app_runtime.
CREATE POLICY "subscription_periods_tenant_read" ON "subscription_periods"
  FOR SELECT TO app_runtime
  USING (workspace_id = NULLIF(current_setting('app.workspace_id', true), '')::uuid);
--> statement-breakpoint
GRANT SELECT ON public.subscription_periods TO app_runtime;
--> statement-breakpoint
-- Worker reads the ledger cross-tenant to promote a due future period into the
-- current aggregate (mirrors the expiry scan's broad worker SELECT). No writes.
CREATE POLICY "subscription_periods_worker_read" ON "subscription_periods"
  FOR SELECT TO app_worker USING (true);
--> statement-breakpoint
GRANT SELECT ON public.subscription_periods TO app_worker;
--> statement-breakpoint
-- Platform admin (trusted billing writer): read all + append (INSERT) only.
CREATE POLICY "subscription_periods_platform_admin_read" ON "subscription_periods"
  FOR SELECT TO app_platform_admin USING (true);
--> statement-breakpoint
CREATE POLICY "subscription_periods_platform_admin_insert" ON "subscription_periods"
  FOR INSERT TO app_platform_admin WITH CHECK (true);
--> statement-breakpoint
GRANT SELECT, INSERT ON public.subscription_periods TO app_platform_admin;
--> statement-breakpoint
-- Scheduled-downgrade pending state (minimal) on the subscriptions aggregate. A
-- downgrade is a FUTURE-renewal target only — it never changes the current plan.
-- Presence of pending_plan_code = a scheduled downgrade exists (at most one).
ALTER TABLE "subscriptions" ADD COLUMN IF NOT EXISTS "pending_plan_code" text;
--> statement-breakpoint
ALTER TABLE "subscriptions" ADD COLUMN IF NOT EXISTS "pending_billing_cycle" text;
--> statement-breakpoint
ALTER TABLE "subscriptions" ADD COLUMN IF NOT EXISTS "pending_change_requested_at" timestamptz;
--> statement-breakpoint
ALTER TABLE "subscriptions" ADD COLUMN IF NOT EXISTS "pending_change_requested_by" uuid;
--> statement-breakpoint
ALTER TABLE "subscriptions" ADD CONSTRAINT "subscriptions_pending_plan_code_check" CHECK ("pending_plan_code" IS NULL OR "pending_plan_code" IN ('STARTER', 'GROWTH', 'PROFESSIONAL', 'ADVANCED', 'BUSINESS', 'BUSINESS_PLUS'));
--> statement-breakpoint
ALTER TABLE "subscriptions" ADD CONSTRAINT "subscriptions_pending_billing_cycle_check" CHECK ("pending_billing_cycle" IS NULL OR "pending_billing_cycle" IN ('MONTHLY', 'ANNUAL'));
--> statement-breakpoint
-- A scheduled downgrade requires all-or-nothing pending fields (no partial state).
ALTER TABLE "subscriptions" ADD CONSTRAINT "subscriptions_pending_all_or_none_check" CHECK (
  ("pending_plan_code" IS NULL AND "pending_billing_cycle" IS NULL AND "pending_change_requested_at" IS NULL AND "pending_change_requested_by" IS NULL)
  OR
  ("pending_plan_code" IS NOT NULL AND "pending_billing_cycle" IS NOT NULL AND "pending_change_requested_at" IS NOT NULL AND "pending_change_requested_by" IS NOT NULL)
);
--> statement-breakpoint
ALTER TABLE "subscriptions" ADD CONSTRAINT "subscriptions_pending_change_requested_by_users_id_fk" FOREIGN KEY ("pending_change_requested_by") REFERENCES "public"."users"("id") ON DELETE set null;
--> statement-breakpoint
-- Owner (app_runtime) may schedule / cancel its OWN downgrade — pending_* only,
-- never the active commercial columns (those stay app_platform_admin per 0062).
GRANT UPDATE ("pending_plan_code", "pending_billing_cycle", "pending_change_requested_at", "pending_change_requested_by", "updated_at", "version") ON public.subscriptions TO app_runtime;
--> statement-breakpoint
-- Platform admin clears pending on a confirmed renewal that consumes it.
GRANT UPDATE ("pending_plan_code", "pending_billing_cycle", "pending_change_requested_at", "pending_change_requested_by") ON public.subscriptions TO app_platform_admin;
--> statement-breakpoint
-- Worker promotes a due future period into the current aggregate at the period
-- boundary: it copies an ALREADY-committed ledger period's plan/price into the
-- aggregate (it never invents commercial data) and clears consumed pending_*.
GRANT UPDATE ("plan_code", "billing_cycle", "current_price_minor", "price_currency_code", "plan_price_version", "pending_plan_code", "pending_billing_cycle", "pending_change_requested_at", "pending_change_requested_by") ON public.subscriptions TO app_worker;
